services:
  - type: web
    name: ilja-alrimi-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22.5.0
